### PR TITLE
skip_misc extras

### PR DESCRIPTION
**Pull request by ValVichGit**
Compile & check before you accept the pull.
This might not work.

### CODE REVIEW

**Comment by ValVichGit** [comment]
No idea why that is conflicting, but the only change you should need would be commits 4d0bacf and a850f24

**Comment by mrpopot** [comment]
radar works with these commit

**Comment by vdepagter** [comment]
So we only need 4d0bacf and a850f24?
Are 8122a9f 0c238c1 f651b6a just optimizations or was that just part of the troubleshooting process?
Thanks!

**Comment by Spectyy** [comment]
So we only need 4d0bacf and a850f24?
Are 8122a9f 0c238c1 f651b6a just optimizations or was that just part of the troubleshooting process?
Thanks!

**Comment by devpup91** [comment]
I applied this change manually in 2118feb4357f73cb2477dbb34563015ba8776d77. Thanks a lot!

**Comment by ucectoplasm** [comment]
I applied this change manually in 2118feb4357f73cb2477dbb34563015ba8776d77. Thanks a lot! Let me know if there are any more issues!

**Pull request closed without merging**
